name: TEMPLATE
version: 0.1
author: Daxelarne
main: knightworld.daxelarne.TEMPLATE.Main
api-version: 1.19
softdepend: [PlaceholderAPI]

commands:
  MACOMMANDE:
    description: DESCRIPTION
    usage: /<command> clear|<titre>

    
permissions:
  PERMISSION:
    description: PERMISSION
    default: op
